export interface TermDef {
  id: string;
  /** The exact label the UI renders (also the highlight target). */
  label: string;
  /** Tooltip line, <= 120 chars, mechanical truth in plain words. */
  short: string;
  /** Expanded codex-of-terms entry; null until a UI plan needs the long form. */
  entry: string | null;
}

export const TERMS: Record<string, TermDef> = {
  // ── the rumor machine ──
  'family':          { id: 'family', label: 'Story', short: 'One rumor and all its mutated versions share a family — different tellings of the same story.', entry: null },
  'version':         { id: 'version', label: 'Version', short: 'The exact wording one mind holds. Versions differ where minds changed them.', entry: null },
  'diff':            { id: 'diff', label: 'Difference', short: 'The changed fields between two versions — each change fingerprints the mind that made it.', entry: null },
  'attribution':     { id: 'attribution', label: 'Source (claimed)', short: 'Who the story SAYS it came from. Mutable, often wrong — and the key to tracing.', entry: null },
  // ── the structured claim (the seven fields every telling carries) ──
  'subject':         { id: 'subject', label: 'Subject', short: 'Who a claim is about — the person the story targets. Attributors and vaguers move it.', entry: null },
  'predicate':       { id: 'predicate', label: 'Predicate', short: 'What a claim alleges — the deed itself. Neutral deeds moralize into sins as they spread.', entry: null },
  'object':          { id: 'object', label: 'Object', short: 'A claim\'s second party — the accomplice or counterparty, when the deed names one.', entry: null },
  'count':           { id: 'count', label: 'Count', short: 'How many, in a claim that counts. Exaggerators double it; minimizers halve it.', entry: null },
  'severity':        { id: 'severity', label: 'Severity', short: 'How grave a claim is, 1 to 5. Dramatists max it; peacemakers walk it down.', entry: null },
  'place':           { id: 'place', label: 'Place', short: 'Where a claim says the deed happened. Relocators strip it away to "somewhere".', entry: null },
  'corroboration':   { id: 'corroboration', label: 'Corroboration', short: 'Hearing a story from apparently independent sources. Manufactured independence still counts.', entry: null },
  'apparent-source': { id: 'apparent-source', label: 'Apparent source', short: 'Who a hearer THINKS a telling came from — the surviving attribution, or the teller.', entry: null },
  'credence':        { id: 'credence', label: 'Credence', short: 'How much a mind believes a story, 0 to 1. Trust, plausibility, and corroboration move it.', entry: null },
  'stance':          { id: 'stance', label: 'Stance', short: 'Belief tiers: dismiss (<0.2), repeat (0.5+), believe (0.75+). Acting takes believing.', entry: null },
  'freshness':       { id: 'freshness', label: 'Freshness', short: 'Stories go stale in ~3 days unless newly corroborated. Stale news is not retold.', entry: null },
  'juiciness':       { id: 'juiciness', label: 'Juiciness', short: 'How tellable a story is on its own. Juicy stories race; dull ones die.', entry: null },
  'circle':          { id: 'circle', label: 'Circle', short: 'A conversation at a venue. Same circle = hear; same venue = see who is present.', entry: null },
  'overheard':       { id: 'overheard', label: 'Overheard', short: 'Heard without being addressed. Bystanders catch words by the same physics as guards.', entry: null },
  'access':          { id: 'access', label: 'Access', short: 'Venues are public, invitational, or private. Standing decides which doors open.', entry: null },
  'bridge':          { id: 'bridge', label: 'Bridge', short: 'A person who frequents two districts. Stories cross firebreaks only on their feet.', entry: null },
  'firebreak':       { id: 'firebreak', label: 'Firebreak', short: 'Districts that share no venues. Rumors cannot jump them without a bridge.', entry: null },
  // ── secrets and sources ──
  'secret':          { id: 'secret', label: 'Secret', short: 'A true thing someone witnessed. Never volunteered — extracted by trust or compulsion.', entry: null },
  'discretion':      { id: 'discretion', label: 'Held close', short: 'A belief its holder will not gossip about. Trust above 0.7, or authority, unlocks it.', entry: null },
  'witnessed':       { id: 'witnessed', label: 'Witnessed', short: 'Known first-hand, not heard. Witnessed beliefs are near-certain and start silent.', entry: null },
  'via':             { id: 'via', label: 'Via', short: 'The channel an entry reached you through: your own eyes, the dossier, or a named informant.', entry: null },
  'informant':       { id: 'informant', label: 'Informant', short: 'A townsperson on your payroll. Their reports pass through THEIR traits — eyes can lie.', entry: null },
  'dossier':         { id: 'dossier', label: 'Dossier', short: 'Your day-0 briefing. Everything in it is true — and never enough.', entry: null },
  // ── your boards ──
  'evidence-board':  { id: 'evidence-board', label: 'Evidence Board', short: 'Auto-collects what you lawfully heard, clusters versions, highlights diffs. Thinking stays yours.', entry: null },
  'codex':           { id: 'codex', label: 'Codex', short: 'Your trait deductions. Propose a trait, corroborate from observed pairs, lock at three.', entry: null },
  'lock':            { id: 'lock', label: 'Lock', short: 'Three corroborating observations confirm a codex hypothesis. Locks trust your channels.', entry: null },
  'fingerprint':     { id: 'fingerprint', label: 'Fingerprint', short: 'The tell-tale change pattern a trait leaves on stories it retells.', entry: null },
  'counter-sketch':  { id: 'counter-sketch', label: 'Counter-Sketch', short: 'Your sketch of HIS sketch — what you believe the enemy has pieced together about you.', entry: null },
  'hypothesis-card': { id: 'hypothesis-card', label: 'Card', short: 'Your written hunch with your confidence. The game files it and never grades it.', entry: null },
  'assist-level':    { id: 'assist-level', label: 'Assist', short: 'Perception help, 0-3: raw notes, clustering+diffs, trait candidates, route sketches.', entry: null },
  'web-view':        { id: 'web-view', label: 'Web', short: 'The provenance web around a subject: which stories touch it, and who carried each hop to you.', entry: null },
  'ledger':          { id: 'ledger', label: 'Ledger', short: 'One channel\'s whole record — every report a via filed, and which stories other channels also carried.', entry: null },
  'evening-report':  { id: 'evening-report', label: 'Evening report', short: 'The day\'s haul, batched: new stories, who brought each, and every authority sighting.', entry: null },
  'day-planner':     { id: 'day-planner', label: 'Planner', short: 'Pause to plan: travel, tell a circle-mate, ask, post informants. Verbs queue for their next beat.', entry: null },
  'terms-codex':     { id: 'terms-codex', label: 'Terms', short: 'The glossary of every game term — hover any label for its meaning, or read them all here.', entry: null },
  // ── your verbs (the planner's logged actions) ──
  'verb-travel':     { id: 'verb-travel', label: 'Travel', short: 'Move your avatar to a venue. Takes effect on the very next tick the sim steps.', entry: null },
  'verb-tell':       { id: 'verb-tell', label: 'Tell', short: 'Speak a story to a circle-mate, under full physics. Fires on the next conversation beat.', entry: null },
  'verb-ask':        { id: 'verb-ask', label: 'Ask', short: 'Ask the circle-mate you name about a story or a person — fires next beat, addressed to exactly them, and observable.', entry: null },
  'verb-post':       { id: 'verb-post', label: 'Post informant', short: 'Ask an informant for a mid-day post at a venue. It is a REQUESTED post until they take it up themselves.', entry: null },
  'verb-note':       { id: 'verb-note', label: 'Margin note', short: 'Pin a private note to anything. Read by nothing in the town — a hunch, never evidence.', entry: null },
  'verb-recruit':    { id: 'verb-recruit', label: 'Recruit', short: 'Approach an in-circle NPC with one of the four MICE handles. They accept, refuse, or ask for time. Priced.', entry: null },
  'verb-set-drop':   { id: 'verb-set-drop', label: 'Set dead drop', short: 'Place a dead drop at a public venue; a courier tasked via it skips the face handoff — no meeting, co-location broken.', entry: null },
  'verb-courier':    { id: 'verb-courier', label: 'Courier', short: 'Ask an asset to carry your story to a target. They judge the moment; any telling rides their traits.', entry: null },
  'verb-meet':       { id: 'verb-meet', label: 'Meet', short: 'Offer one asset a safehouse rendezvous. Only their own acceptance ever puts them in the room.', entry: null },
  'verb-host':       { id: 'verb-host', label: 'Host', short: 'Send invitations to a salon or back-room evening. Each guest answers for themselves. Priced, and on the record.', entry: null },
  'verb-debrief':    { id: 'verb-debrief', label: 'Debrief', short: 'Compel an asset at the safehouse to answer, bypassing their discretion. Costs their trust and a strike.', entry: null },
  'verb-sell':       { id: 'verb-sell', label: 'Sell', short: 'Sell a story to a circle-mate for coin. Priced by its severity — and selling it leaks it, same as telling.', entry: null },
  'verb-directive':  { id: 'verb-directive', label: 'Directive', short: 'Hand an outcome brief to a present asset or relay; they decide how to act, and any report must travel back.', entry: null },
  'verb-forge':      { id: 'verb-forge', label: 'Forge', short: 'Commission a forged document carrying a fixed claim. Priced, and the ink needs a day to dry.', entry: null },
  'verb-plant':      { id: 'verb-plant', label: 'Plant', short: 'Leave a document where it will be found, or hand it to a circle-mate. Never both at once.', entry: null },
  'verb-show':       { id: 'verb-show', label: 'Show', short: 'Hold a document up to a circle-mate and keep it. Paper is believed further than any mouth.', entry: null },
  'verb-scry': { id: 'verb-scry', label: 'Scry', short: 'Buy a remote scene tomorrow: up to an hour, in 15-minute steps. Costs 15 coin and leaves physical residue.', entry: null },
  'scrying': { id: 'scrying', label: 'Scrying', short: 'A view of one venue as events happen. It shows words faithfully; the words themselves may be false.', entry: null },
  'magic': { id: 'magic', label: 'Magic', short: 'Observation through a ritual. It supplies no independent informant channel.', entry: null },
  'scene-presence': { id: 'scene-presence', label: 'Seen in the scene', short: 'A person visible at a known venue and time. Presence alone does not say they serve the watch.', entry: null },
  'arcane-residue': { id: 'arcane-residue', label: 'Arcane residue', short: 'A physical trace where scrying begins. Local witnesses may report it; it does not name the caster.', entry: null },
  'verb-seance': { id: 'verb-seance', label: 'Hold a séance',
    short: '20 coin, once per campaign. A chapel or cathedral before 04:00. The departed gives testimony and one relationship.', entry: null },
  'the-departed': { id: 'the-departed', label: 'The departed',
    short: 'A historical witness whose account survives: a true secret and one real relationship.', entry: null },
  'night-visit': { id: 'night-visit', label: 'Night visit',
    short: 'A chapel or cathedral visit before 04:00. A guard must report it; the spymaster can witness it directly.', entry: null },
  // ── the network economy: your standing, your payroll, your reach (Plan 8) ──
  'station':         { id: 'station', label: 'Station', short: 'The seat the seed deals your avatar — noble or lowlife. Fixed for the campaign; it sets your standing in town.', entry: null },
  'standing':        { id: 'standing', label: 'Standing', short: 'What your station lets you do: which venue doors open without suspicion, and the one room you may host in.', entry: null },
  'noble':           { id: 'noble', label: 'Noble', short: 'The high-born station. Opens the salon and hosts its evenings there; the back rooms stay shut to you.', entry: null },
  'lowlife':         { id: 'lowlife', label: 'Lowlife', short: 'The low-born station. Opens the back rooms and hosts their evenings; the salon stays shut to you.', entry: null },
  'salon':           { id: 'salon', label: 'Salon', short: 'The noble\'s invitational room. A noble\'s standing opens it and hosts salon evenings; a lowlife is shut out.', entry: null },
  'back-room':       { id: 'back-room', label: 'Back room', short: 'The lowlife\'s invitational room. A lowlife\'s standing opens it and hosts evenings there; a noble is shut out.', entry: null },
  'hosting':         { id: 'hosting', label: 'Hosting', short: 'An evening in your own room. You send the invitations; each guest decides. Priced, and the list is on the record.', entry: null },
  'recruit':         { id: 'recruit', label: 'Recruit', short: 'Ask a townsperson to serve, through one of the four MICE handles — they answer for themselves, each handle its own way.', entry: null },
  'mice-money':      { id: 'mice-money', label: 'Money', short: 'Money buys fast — and leaks to higher bidders. The one handle with no conviction or leverage behind it.', entry: null },
  'mice-ideology':   { id: 'mice-ideology', label: 'Ideology', short: 'Ideology binds hardest — but won\'t carry or give up a smear against its own faction, even under pressure.', entry: null },
  'mice-coercion':   { id: 'mice-coercion', label: 'Coercion', short: 'Coercion holds by leverage, so their trust starts lowest — the handle nearest to turning against you.', entry: null },
  'mice-ego':        { id: 'mice-ego', label: 'Ego', short: 'Ego is bought with flattery — and their own reports inflate: every count and grievance exaggerated.', entry: null },
  'courier':         { id: 'courier', label: 'Courier', short: 'An asset carrying your story toward a target on their own schedule and their own judgement of the moment.', entry: null },
  'dead-drop':       { id: 'dead-drop', label: 'Dead drop', short: 'A cache at a public venue a courier learns, so the handoff skips co-location — no meeting of yours to be seen.', entry: null },
  'compartment':     { id: 'compartment', label: 'Compartment', short: 'What an asset knows — who recruited them, which drops and ops they carried. Interrogation reads exactly this.', entry: null },
  'walk-in':         { id: 'walk-in', label: 'Walk-in', short: 'An enemy asset who has flipped to you — unbidden, they hand over a real piece of his sketch each week.', entry: null },
  'turncoat':        { id: 'turncoat', label: 'Turncoat', short: 'An asset whose reports quietly stop matching reality — cross-check your channels to catch one.', entry: null },
  'debrief':         { id: 'debrief', label: 'Debrief', short: 'Compelling your own asset to answer at the safehouse — it bypasses their discretion at the cost of their trust.', entry: null },
  'stipend':         { id: 'stipend', label: 'Stipend', short: 'The fixed sum the treasury draws each rest-day week — your steady income. It never grows, so spend deliberately.', entry: null },
  'wage':            { id: 'wage', label: 'Wage', short: 'What each asset draws from the treasury weekly. Miss it and they take a strike, and their trust slides.', entry: null },
  'brokerage':       { id: 'brokerage', label: 'Brokerage', short: 'Selling a story you hold for coin, priced by its severity — and the sale leaks the story, the same as telling it.', entry: null },
  'network':         { id: 'network', label: 'Network', short: 'Your roster at a glance — each asset\'s wages, strikes, posting, and how much they\'ve learned. Trust you infer.', entry: null },
  'treasury':        { id: 'treasury', label: 'Treasury', short: 'Your coin, the next stipend, and what every verb costs — money prices your choices, it is never a second game.', entry: null },
  // ── the directive network: you set the mission, the asset owns the moment (Plan 11) ──
  'directive':       { id: 'directive', label: 'Directive', short: 'An outcome brief handed to an asset. They read the real situation and decide how — or whether — to act.', entry: 'A directive is a request that travels. You author the mission and every handoff lever, hand it to someone standing in front of you, and it walks the rest of the way on real feet through real conversations. What arrives may not be what you wrote: each relay is a mind, and minds shorten, soften, embellish, and forget. The recipient reads the version that actually reached them, against the situation actually in front of them, and may refuse, defer, attempt it literally, adapt it, or abort. The desk shows you what YOU wrote and what physically came back — never whether it arrived, never what they decided.' },
  'brief':           { id: 'brief', label: 'Brief', short: 'The authored body of a directive: mission, levers, window, purpose. Only a received copy can be acted on.', entry: 'The brief is the object you compose. It is not the object your recipient obeys: the copy that physically reaches them is the only executable one, and it carries whatever mutations the route put into it. Your ledger keeps the pristine version you wrote, because that is what you know. The two can differ by a name, a deadline, or the whole point — and nothing in the game will tell you which.' },
  'priority':        { id: 'priority', label: 'Priority', short: 'How urgently you framed the mission: routine, important, or urgent. One lever among eight, never a score.', entry: null },
  'purpose':         { id: 'purpose', label: 'Purpose', short: 'The why you chose to share — or withheld. Sharing it buys understanding and costs a secret if the brief is read.', entry: null },
  'report-expectation': { id: 'report-expectation', label: 'Report expectation', short: 'How much you asked to hear back: nothing, the outcome, the reasoning, or the full account.', entry: null },
  'scrutiny':        { id: 'scrutiny', label: 'Scrutiny', short: 'How closely an asset believes they are being watched. Inferred from your treatment of them — never a shown meter.', entry: 'Scrutiny is a belief inside someone else\'s head, built only from things they could actually observe: being questioned, leaned on with authority, retasked, cut out of something, or confronted. It decays on its own. It is never a meter: no number, no bar, and no selector anywhere in this game exposes it, because a meter would turn a person into an instrument. You infer it the way you would infer it in life — from how guarded they have become since the last time you pushed. High scrutiny guards loyal people exactly as readily as disloyal ones, so guarded behaviour is never proof of betrayal.' },
  'sound-out':       { id: 'sound-out', label: 'Sound out', short: 'Send an asset to gauge someone\'s willingness or arrange a meeting. It never enrolls anyone.', entry: 'Sounding out is reconnaissance on a person. An asset raises the subject, watches the answer, and reports what they observed — willingness voiced, a meeting agreed, a door closed. It cannot recruit: final enrollment stays a moment your avatar is physically present for. The report says what was observed, not a grade; there is no eligibility score behind it to reveal.' },
  'runaround':       { id: 'runaround', label: 'Runaround', short: 'A false lead the enemy spends real nights chasing. It burns his attention only while his own evidence supports it.', entry: null },
  // ── the hunt ──
  'sketch':          { id: 'sketch', label: 'Ghost sketch', short: 'The enemy investigates a ghost — every traced operation adds a feature to it.', entry: null },
  'sketch-feature':  { id: 'sketch-feature', label: 'Feature', short: 'One deduced trait of the ghost: a district, an entry point, a carrier profile.', entry: null },
  'watch':           { id: 'watch', label: 'Watch', short: 'Guards posted to a district evening after evening. A countermeasure you can SEE.', entry: null },
  'interrogation':   { id: 'interrogation', label: 'Interrogation', short: 'A named target compelled to answer at an invitational venue. Authority opens mouths.', entry: null },
  'inquiry':         { id: 'inquiry', label: 'Asking-around', short: 'Someone is asking questions about a story or a person. Asking is itself observable.', entry: null },
  'authority':       { id: 'authority', label: 'With authority', short: 'A question carrying the watch\'s weight. Refusing discretion does not survive it.', entry: null },
  'exposure':        { id: 'exposure', label: 'Exposure', short: 'How much of the ghost sketch points at YOUR people. Distinct features, never raw count.', entry: null },
  'pressure':        { id: 'pressure', label: 'Pressure', short: 'How exposed you are: score 3+ doubles the enemy nightly watches; score 5+ also doubles his interrogations.', entry: null },
  'identified':      { id: 'identified', label: 'Identified', short: 'The carrier profile has your face. The hunt is over unless you already won.', entry: null },
  // ── the campaign ──
  'doom-clock':      { id: 'doom-clock', label: 'Doom clock', short: 'The campaign\'s natural deadline. Day 40: the coronation happens with or without you.', entry: null },
  'council':         { id: 'council', label: 'Council', short: 'The electors. When enough of them believe the worst, they act — that is your win.', entry: null },
  'usurper':         { id: 'usurper', label: 'Usurper', short: 'The one about to be crowned. Your objective walks and talks and has secrets.', entry: null },
  'denounce':        { id: 'denounce', label: 'Denunciation', short: 'The council turns on the usurper — an institutional act the town itself performs.', entry: null },
  'coronation':      { id: 'coronation', label: 'Coronation', short: 'The clock ran out. The crown lands; the campaign is lost.', entry: null },
  'unmasking':       { id: 'unmasking', label: 'Unmasking', short: 'The enemy\'s sketch converged on you. The slow loss, arrived.', entry: null },
  'arrest':          { id: 'arrest', label: 'Arrest', short: 'A guard heard you speak the words yourself — caught in the act. The campaign ends in the cell.', entry: null },
  'objective-topple':{ id: 'objective-topple', label: 'Topple the usurper', short: 'Turn the council before day 40: quorum of electors believing act-tier dirt on the usurper.', entry: null },
  // ── vignettes ──
  'vignette-public-quarrel':   { id: 'vignette-public-quarrel', label: 'Public quarrel', short: 'Two rivals who each believe the worst finally collide in public. The town takes notes.', entry: null },
  'vignette-merchant-ruin':    { id: 'vignette-merchant-ruin', label: 'Ruin', short: 'When enough creditors believe the bankruptcy, the shop shutters — visibly.', entry: null },
  'vignette-broken-betrothal': { id: 'vignette-broken-betrothal', label: 'Broken betrothal', short: 'A lover who believes the affair breaks it off. Love turns rival; kin hear why.', entry: null },
  // ── traits (trait-<id>) ──
  'trait-exaggerator': { id: 'trait-exaggerator', label: 'Exaggerator', short: 'Numbers double and severity climbs each retelling. Storyteller scale.', entry: null },
  'trait-attributor':  { id: 'trait-attributor', label: 'Attributor', short: 'Fills a vague "someone" with a name from their own grudges. Vague claims are loaded guns.', entry: null },
  'trait-moralizer':   { id: 'trait-moralizer', label: 'Moralizer', short: 'Rewrites deeds into the sin register: a night meeting becomes an affair.', entry: null },
  'trait-partisan':    { id: 'trait-partisan', label: 'Partisan', short: 'Softens their faction\'s sins, sharpens the rival\'s. Fires on faction-relevant claims only.', entry: null },
  'trait-skeptic':     { id: 'trait-skeptic', label: 'Skeptic', short: 'Retells nothing uncorroborated. A gatekeeper where rumors go to die.', entry: null },
  'trait-literalist':  { id: 'trait-literalist', label: 'Literalist', short: 'Passes stories through unchanged. Rare, precious routing infrastructure.', entry: null },
  'trait-minimizer':   { id: 'trait-minimizer', label: 'Minimizer', short: 'Halves counts and walks severity down one. Everything was probably fine.', entry: null },
  'trait-dramatist':   { id: 'trait-dramatist', label: 'Dramatist', short: 'Any damaging story lands at maximum severity. There are no small scandals.', entry: null },
  'trait-name-dropper':{ id: 'trait-name-dropper', label: 'Name-dropper', short: 'Swaps a named source for a name from their own grudges. Breaks your traces.', entry: null },
  'trait-vaguener':    { id: 'trait-vaguener', label: 'Vague teller', short: 'Named sources dissolve into "someone". The fog that kills traceroutes.', entry: null },
  'trait-numberer':    { id: 'trait-numberer', label: 'Numberer', short: 'Invents a count of exactly three where the story had none.', entry: null },
  'trait-peacemaker':  { id: 'trait-peacemaker', label: 'Peacemaker', short: 'Walks damaging stories down two severity steps. Surely it was a misunderstanding.', entry: null },
  'trait-objectifier': { id: 'trait-objectifier', label: 'Objectifier', short: 'Drags a grudge-list name into the story\'s empty accomplice slot.', entry: null },
  'trait-relocator':   { id: 'trait-relocator', label: 'Relocator', short: 'Strips the where from stories. It happened somewhere or other.', entry: null },
  // ── predicates (predicate-<id>) ──
  'predicate-met-secretly-with':           { id: 'predicate-met-secretly-with', label: 'Met secretly with', short: 'A claim of an unwitnessed meeting — juicy on its own; one moralizing retelling from becoming an affair.', entry: null },
  'predicate-is-having-an-affair-with':     { id: 'predicate-is-having-an-affair-with', label: 'Having an affair', short: 'An accusation of an affair — the moralizer\'s final landing spot; no sin-version sits above it.', entry: null },
  'predicate-stole':                        { id: 'predicate-stole', label: 'Stole', short: 'An accusation of theft — faction-relevant, and the sin-version several lesser claims moralize into.', entry: null },
  'predicate-is-bankrupt':                  { id: 'predicate-is-bankrupt', label: 'Bankrupt', short: 'A claim of financial ruin — faction-relevant, and the credence the merchant-ruin vignette watches for.', entry: null },
  'predicate-owes-money-to':                { id: 'predicate-owes-money-to', label: 'Owes money to', short: 'A claim of unpaid debt — mild alone; one moralizing retelling turns it into an accusation of theft.', entry: null },
  'predicate-poisoned':                     { id: 'predicate-poisoned', label: 'Poisoned', short: 'An accusation of poisoning — the gravest dirt in the game; the watch treats it as treason talk.', entry: null },
  'predicate-forged-the-lineage':           { id: 'predicate-forged-the-lineage', label: 'Forged the lineage', short: 'An accusation of a falsified bloodline — faction-relevant, and among the juiciest claims in play.', entry: null },
  'predicate-plans-to-seize-the-throne':    { id: 'predicate-plans-to-seize-the-throne', label: 'Plans to seize the throne', short: 'A claim of plotting the crown — faction-relevant; believed dirt like this is what topples a usurper.', entry: null },
  'predicate-bribed-the-council':           { id: 'predicate-bribed-the-council', label: 'Bribed the council', short: 'An accusation of buying votes — faction-relevant corruption aimed straight at the council\'s credence.', entry: null },
  'predicate-embezzles-guild-funds':        { id: 'predicate-embezzles-guild-funds', label: 'Embezzles guild funds', short: 'An accusation of skimming guild coin — faction-relevant, and comfortably juicy on its own.', entry: null },
  'predicate-consorts-with-smugglers':      { id: 'predicate-consorts-with-smugglers', label: 'Consorts with smugglers', short: 'A claim of smuggler dealings — faction-relevant; guilt by association still counts as dirt.', entry: null },
  'predicate-cheats-at-cards':              { id: 'predicate-cheats-at-cards', label: 'Cheats at cards', short: 'An accusation of card-sharping — petty and faction-neutral; one retelling from being called theft.', entry: null },
  'predicate-fathered-a-bastard':           { id: 'predicate-fathered-a-bastard', label: 'Fathered a bastard', short: 'A claim of an unacknowledged child — faction-neutral; one moralizing retelling from an affair charge.', entry: null },
  'predicate-broke-a-betrothal':            { id: 'predicate-broke-a-betrothal', label: 'Broke a betrothal', short: 'A claim of a broken engagement — faction-neutral, and the claim the broken-betrothal vignette mints.', entry: null },
  'predicate-publicly-quarreled-with':      { id: 'predicate-publicly-quarreled-with', label: 'Publicly quarreled with', short: 'A claim of an open falling-out — faction-neutral, and the claim the public-quarrel vignette mints.', entry: null },
  'predicate-shuttered-the-shop':           { id: 'predicate-shuttered-the-shop', label: 'Shuttered the shop', short: 'A claim the shop has closed — faction-neutral, the visible proof the merchant-ruin vignette produces.', entry: null },
  'predicate-blessed-the-harvest':          { id: 'predicate-blessed-the-harvest', label: 'Blessed the harvest', short: 'A flattering claim of good fortune — faction-neutral, and the least tellable line in the registry.', entry: null },
  'predicate-rescued-the-drowning-child':   { id: 'predicate-rescued-the-drowning-child', label: 'Rescued the drowning child', short: 'A flattering claim of heroism — faction-neutral, and surprisingly juicy for good news.', entry: null },
  'predicate-gave-alms-to-the-poor':        { id: 'predicate-gave-alms-to-the-poor', label: 'Gave alms to the poor', short: 'A flattering claim of charity — faction-neutral and only modestly tellable.', entry: null },
  'predicate-won-the-regatta':              { id: 'predicate-won-the-regatta', label: 'Won the regatta', short: 'A flattering claim of a sporting win — faction-neutral, middling juiciness.', entry: null },
  'predicate-is-favored-at-court':          { id: 'predicate-is-favored-at-court', label: 'Favored at court', short: 'A flattering claim of royal favor — faction-relevant; the partisan trait sharpens or softens it by side.', entry: null },
  'predicate-nursed-the-sick-through-fever':{ id: 'predicate-nursed-the-sick-through-fever', label: 'Nursed the sick through fever', short: 'A flattering claim of nursing the sick — faction-neutral and only modestly tellable.', entry: null },
  'predicate-is-the-true-heir-of':          { id: 'predicate-is-the-true-heir-of', label: 'The true heir', short: 'A claim of true parentage to the throne — faction-relevant, and nearly as juicy as poison itself.', entry: null },
  'predicate-met-at-the-docks-by-night':    { id: 'predicate-met-at-the-docks-by-night', label: 'Met at the docks by night', short: 'A neutral claim of a night meeting at the docks — one retelling from being called a secret meeting.', entry: null },
  // Terminal-only debrief vocabulary (Task 7B).
  "terminal-debrief": {"id": "terminal-debrief", "label": "Debrief", "short": "The campaign has ended. Read retained causes, received copies and what remains unknown.", "entry": null},
  "artifact": {"id": "artifact", "label": "Artifact", "short": "A physical document has fixed text; each viewing can begin a separate story.", "entry": null},
  "forgery": {"id": "forgery", "label": "Forgery", "short": "A commissioned document. Its paper stays fixed while people can change their accounts of it.", "entry": null},
  "seance": {"id": "seance", "label": "Séance", "short": "Later testimony from the departed. It does not create a new historical claim or prove a visible visit was a ritual.", "entry": null},
  "thread": {"id": "thread", "label": "Thread", "short": "Follow one retained story, operation or report root without merging unrelated identities.", "entry": null},
  "timeline": {"id": "timeline", "label": "Sketch timeline", "short": "Observation, receipt, acquisition and the enemy’s later conclusions keep their actual dates.", "entry": null},
  "overlay": {"id": "overlay", "label": "Overlay", "short": "Compare received signals with actual attention and resulting features, keeping unproved links explicit.", "entry": null},
  "phantom": {"id": "phantom", "label": "Phantom", "short": "A fabricated appearance of attention requires evidence of fabrication; missing history does not prove it.", "entry": null},
  "lag": {"id": "lag", "label": "Lag", "short": "Actual attention without a matched received signal is shown separately from features without signal links.", "entry": null},
  "debrief-epigraph": {"id": "debrief-epigraph", "label": "what can happen, not what will happen", "short": "Each campaign teaches possibilities in the information system, not an answer key for another seed.", "entry": null},
  "unrecorded": {"id": "unrecorded", "label": "Unrecorded", "short": "The retained history does not supply this fact. A missing record is not proof that nothing happened.", "entry": null},
  "ambiguous": {"id": "ambiguous", "label": "Ambiguous", "short": "More than one retained candidate fits. No candidate is silently chosen.", "entry": null},
  "reported-account": {"id": "reported-account", "label": "Reported account", "short": "What someone said or headquarters heard; it may differ from the actual work.", "entry": null},
  "actual-attention": {"id": "actual-attention", "label": "Actual attention", "short": "Retained performed questioning, compelled answers or staffed watch work, separate from resulting evidence.", "entry": null},
  "claim-change": {"id": "claim-change", "label": "Claim change", "short": "An exact change between retained claim fields. A responsible mind is named only when the record supports it.", "entry": null},
  "evidence-arrival": {"id": "evidence-arrival", "label": "Evidence arrival", "short": "When the enemy actually acquired evidence, which may be later than the reported observation.", "entry": null},
  "orphan-history": {"id": "orphan-history", "label": "Unresolved history", "short": "Retained events whose operation, root, receipt or date cannot be resolved remain available to read.", "entry": null},
};
